version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: guinote-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: guinote-secret
      MONGO_INITDB_DATABASE: guinote
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: guinote-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build: ./server
    container_name: guinote-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:guinote-secret@mongodb:27017/guinote?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-production-secret-key
      JWT_REFRESH_SECRET: your-production-refresh-secret
      CLIENT_URL: http://localhost:8081
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data: